name: dart_quickjs
description: QuickJS-ng JavaScript engine bindings for Dart/Flutter.
version: 1.0.0
repository: https://github.com/xiaoyaocz/dart_quickjs
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  code_assets: ^1.0.0
  logging: ^1.2.0
  hooks: ^1.0.0
  native_toolchain_c: 
    path: packages/native_toolchain_c

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
